spring:
  cloud:
    nacos:
      serverAddr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
  config:
    import:
      - nacos:qihang-oms.yaml?refresh=true
  application:
    name: dou-api

server:
  port: 8085


mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.qihang.dou.domain;com.qihang.security.entity;
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启sql日志