spring:
  cloud:
    nacos:
      serverAddr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
  config:
    import:
      - nacos:qihang-oms.yaml?refresh=true
  application:
    name: oms-core

server:
  port: 8083