
spring:
  cloud:
    loadbalancer:
      nacos:
        enabled: true
    nacos:
      serverAddr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
  config:
    import:
      - nacos:qihang-oms.yaml?refresh=true
  application:
    name: oms-api
server:
  port: 8082

#mybatis-plus:
#  mapper-locations: classpath*:mapper/**/*Mapper.xml
#  type-aliases-package: com.qihang.core.domain.entity;com.qihang.erp.api.domain