spring:
  cloud:
    loadbalancer:
      nacos:
        enabled: true
    nacos:
      serverAddr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
        usename: nacos
        passowrd: nacos
#    gateway:
#      discovery:
#        locator:
#          enabled: true # gateway 可以从 nacos 发现微服务
  config:
    import:
      - nacos:qihang-oms.yaml?refresh=true
  application:
    name: oms-api
server:
  port: 8082


#mybatis-plus:
#  mapper-locations: classpath*:mapper/**/*Mapper.xml
#  type-aliases-package: com.qihang.core.domain.entity;com.qihang.erp.api.domain
